services:
  init_prometheus:
    image: prom/prometheus:latest
    user: root
    entrypoint:
      - /bin/sh
      - -c
      - |
        chown -R 65534:65534 /prometheus
    volumes:
      - /home/ec2-user/crowdlytics-api/Data/prometheus:/prometheus
      - /home/ec2-user/crowdlytics-api/Config/prometheus.yml:/etc/prometheus/prometheus.yml

  prometheus:
    image: prom/prometheus:latest
    container_name: PrometheusServer
    restart: always
    ports:
      - 9090:9090
    command: # https://github.com/prometheus/prometheus/issues/6188#issuecomment-619486372
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--storage.tsdb.retention.time=90d'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--web.enable-lifecycle'
    volumes:
      - <YOUR_PATH>/Data/prometheus:/prometheus
      - <YOUR_PATH>/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - prom_network

  dumper:
    image: crowdlytics/dumper:latest
    container_name: CrowdlyticsDataDumper
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - 7000:7000
    environment:
      PYTHONUNBUFFERED: 1
      PROMETHEUS_PORT: "7000"
    networks:
      - prom_network

networks:
  prom_network:
    driver: bridge